# MDK 原样。
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.3.0
minecraft_version_range=[1.20.1,1.21)
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=maidtconstructrangedtools
mod_name=Maid TConstruct: Ranged Tools
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.maidtcr.maidtconstructrangedtools
mod_authors=MaidTCR
mod_description=\u4e3a\u8f66\u4e07\u5973\u4ec6\u6dfb\u52a0\u5320\u9b42 3 \u7684\u8fdc\u7a0b\u5de5\u5177\u5de5\u4f5c\u6a21\u5f0f\uff1a\u5f29\u3001\u9493\u9c7c\u7aff\uff08\u5df2\u7981\u7528\uff09\u3001\u6807\u67aa\u3001\u957f\u5f13\u3001\u624b\u91cc\u5251\u3001\u6295\u65a7\u3001\u55b7\u6d41\u5203
